# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

size <- function(n0, m, maxT, p_list_vec, tol) {
    .Call(`_RDSsamplesize_size`, n0, m, maxT, p_list_vec, tol)
}

